### PR TITLE
implement a function to send UIDL command

### PR DESCRIPTION
**Pull request by hebiyan**
Since this library seems to lack the implementation of UIDL command.
So I wrote functions that send the UIDL command and that parse the response from server, based on rfc1939.
Please check my code.

Sorry for my poor english. Thank you.

### CODE REVIEW

**Comment by mattnenterprise** [comment]
First of all thanks for the pull request! Second Its looks to me as the functions `parse_uidl_all` and `parse_uidl_one` do the same thing except for the regex definition. Could you split out the common functionality into a function where you just pass in the regex?

**Comment by mattnenterprise** [comment]
LGTM. Thanks for the pull request!

**Comment by hebiyan** [comment]
Thank you for merging this! I'm happy to help you.

**Comment by TheDarkSkyXD** [comment]
## Tracked on branch `v2.0-async-rewrite`

This issue is being addressed across two milestones:

**v2.0 (Phases 1–4)** — already covers:
- Async/Tokio support (full rewrite)
- UIDL command
- APOP authentication
- STARTTLS/STLS
- Custom timeouts

**v3.0 (Phases 5–9)** — covers the remaining advanced features:
- Phase 5: POP3 command pipelining (RFC 2449)
- Phase 6: UIDL caching for incremental syncs
- Phase 7: Automatic reconnection with exponential backoff
- Phase 8: Connection pooling (multi-account, per RFC 1939 exclusive lock)
- Phase 9: Optional MIME parsing via `mail-parser`

Requirements defined in `.planning/REQUIREMENTS.md`, roadmap in `.planning/ROADMAP.md`.

**Pull request merged**
